version: '2'
services:
  app:
    image: mercari/appengine-go:latest
    working_dir: /go/src/github.com/tyamaguc/gae_test
    command: make serve-dev
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - .:/go/src/github.com/tyamaguc/gae_test
  dep:
    image: instrumentisto/dep:0.3.2
    working_dir: /go/src/github.com/tyamaguc/gae_test
    volumes:
      - .:/go/src/github.com/tyamaguc/gae_test
